export const dayColors = {
  primaryFirst: "#0E0E0E",
  primaryFirstHover: "#262626",
  primaryFirstActive: "#000000",
  backgroundBody: "#F5F7FA",
  backgroundFirst: "#FFFFFF",
  backgroundSecond: "#E4E6E9",
  backgroundThird: "#BABEC5",
  backgroundFourth: "#FFFFFF",
  borderFirst: "#B2C1D8",
  borderFirstFocus: "#0E0E0E",
  textFirst: "#000",
  textSecond: "#FFFFFF",
  iconFirst: "#000",
  success: "#",
  danger: "#E24848",
  divider: "#CDD5E0",
  checked: "#0E0E0E",
  unchecked: "#999",
};
